---
apiVersion: v1
kind: Service
metadata:
  name: cms-website
  namespace: web-dev
  labels:
    app: cms-website
spec:
  type: LoadBalancer
  selector:
    app: cms-website
  ports:
    - port: 50051
