// Code generated by protoc-gen-go. DO NOT EDIT.
// source: content.proto

package content

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Content struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CategoryId           int32    `protobuf:"varint,2,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	TypeId               int32    `protobuf:"varint,4,opt,name=type_id,json=typeId,proto3" json:"type_id,omitempty"`
	Description          string   `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	ThumbnailUrl         string   `protobuf:"bytes,6,opt,name=thumbnail_url,json=thumbnailUrl,proto3" json:"thumbnail_url,omitempty"`
	ContentUrl           string   `protobuf:"bytes,7,opt,name=content_url,json=contentUrl,proto3" json:"content_url,omitempty"`
	Size                 int32    `protobuf:"varint,8,opt,name=size,proto3" json:"size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Content) Reset()         { *m = Content{} }
func (m *Content) String() string { return proto.CompactTextString(m) }
func (*Content) ProtoMessage()    {}
func (*Content) Descriptor() ([]byte, []int) {
	return fileDescriptor_content_0073c56b4875ea38, []int{0}
}
func (m *Content) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Content.Unmarshal(m, b)
}
func (m *Content) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Content.Marshal(b, m, deterministic)
}
func (dst *Content) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Content.Merge(dst, src)
}
func (m *Content) XXX_Size() int {
	return xxx_messageInfo_Content.Size(m)
}
func (m *Content) XXX_DiscardUnknown() {
	xxx_messageInfo_Content.DiscardUnknown(m)
}

var xxx_messageInfo_Content proto.InternalMessageInfo

func (m *Content) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Content) GetCategoryId() int32 {
	if m != nil {
		return m.CategoryId
	}
	return 0
}

func (m *Content) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Content) GetTypeId() int32 {
	if m != nil {
		return m.TypeId
	}
	return 0
}

func (m *Content) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Content) GetThumbnailUrl() string {
	if m != nil {
		return m.ThumbnailUrl
	}
	return ""
}

func (m *Content) GetContentUrl() string {
	if m != nil {
		return m.ContentUrl
	}
	return ""
}

func (m *Content) GetSize() int32 {
	if m != nil {
		return m.Size
	}
	return 0
}

type CreateContentRequest struct {
	CategoryId           int32    `protobuf:"varint,1,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	TypeId               int32    `protobuf:"varint,3,opt,name=type_id,json=typeId,proto3" json:"type_id,omitempty"`
	Description          string   `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	ThumbnailUrl         string   `protobuf:"bytes,5,opt,name=thumbnail_url,json=thumbnailUrl,proto3" json:"thumbnail_url,omitempty"`
	ContentUrl           string   `protobuf:"bytes,6,opt,name=content_url,json=contentUrl,proto3" json:"content_url,omitempty"`
	Size                 int32    `protobuf:"varint,7,opt,name=size,proto3" json:"size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateContentRequest) Reset()         { *m = CreateContentRequest{} }
func (m *CreateContentRequest) String() string { return proto.CompactTextString(m) }
func (*CreateContentRequest) ProtoMessage()    {}
func (*CreateContentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_content_0073c56b4875ea38, []int{1}
}
func (m *CreateContentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateContentRequest.Unmarshal(m, b)
}
func (m *CreateContentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateContentRequest.Marshal(b, m, deterministic)
}
func (dst *CreateContentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateContentRequest.Merge(dst, src)
}
func (m *CreateContentRequest) XXX_Size() int {
	return xxx_messageInfo_CreateContentRequest.Size(m)
}
func (m *CreateContentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateContentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateContentRequest proto.InternalMessageInfo

func (m *CreateContentRequest) GetCategoryId() int32 {
	if m != nil {
		return m.CategoryId
	}
	return 0
}

func (m *CreateContentRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateContentRequest) GetTypeId() int32 {
	if m != nil {
		return m.TypeId
	}
	return 0
}

func (m *CreateContentRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *CreateContentRequest) GetThumbnailUrl() string {
	if m != nil {
		return m.ThumbnailUrl
	}
	return ""
}

func (m *CreateContentRequest) GetContentUrl() string {
	if m != nil {
		return m.ContentUrl
	}
	return ""
}

func (m *CreateContentRequest) GetSize() int32 {
	if m != nil {
		return m.Size
	}
	return 0
}

type CreateContentResponse struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateContentResponse) Reset()         { *m = CreateContentResponse{} }
func (m *CreateContentResponse) String() string { return proto.CompactTextString(m) }
func (*CreateContentResponse) ProtoMessage()    {}
func (*CreateContentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_content_0073c56b4875ea38, []int{2}
}
func (m *CreateContentResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateContentResponse.Unmarshal(m, b)
}
func (m *CreateContentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateContentResponse.Marshal(b, m, deterministic)
}
func (dst *CreateContentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateContentResponse.Merge(dst, src)
}
func (m *CreateContentResponse) XXX_Size() int {
	return xxx_messageInfo_CreateContentResponse.Size(m)
}
func (m *CreateContentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateContentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateContentResponse proto.InternalMessageInfo

func (m *CreateContentResponse) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type GetContentRequest struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetContentRequest) Reset()         { *m = GetContentRequest{} }
func (m *GetContentRequest) String() string { return proto.CompactTextString(m) }
func (*GetContentRequest) ProtoMessage()    {}
func (*GetContentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_content_0073c56b4875ea38, []int{3}
}
func (m *GetContentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetContentRequest.Unmarshal(m, b)
}
func (m *GetContentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetContentRequest.Marshal(b, m, deterministic)
}
func (dst *GetContentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetContentRequest.Merge(dst, src)
}
func (m *GetContentRequest) XXX_Size() int {
	return xxx_messageInfo_GetContentRequest.Size(m)
}
func (m *GetContentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetContentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetContentRequest proto.InternalMessageInfo

func (m *GetContentRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type GetContentsRequest struct {
	CategoryId           int32    `protobuf:"varint,1,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	TypeId               int32    `protobuf:"varint,2,opt,name=type_id,json=typeId,proto3" json:"type_id,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	PageSize             int32    `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageNum              int32    `protobuf:"varint,5,opt,name=page_num,json=pageNum,proto3" json:"page_num,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetContentsRequest) Reset()         { *m = GetContentsRequest{} }
func (m *GetContentsRequest) String() string { return proto.CompactTextString(m) }
func (*GetContentsRequest) ProtoMessage()    {}
func (*GetContentsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_content_0073c56b4875ea38, []int{4}
}
func (m *GetContentsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetContentsRequest.Unmarshal(m, b)
}
func (m *GetContentsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetContentsRequest.Marshal(b, m, deterministic)
}
func (dst *GetContentsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetContentsRequest.Merge(dst, src)
}
func (m *GetContentsRequest) XXX_Size() int {
	return xxx_messageInfo_GetContentsRequest.Size(m)
}
func (m *GetContentsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetContentsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetContentsRequest proto.InternalMessageInfo

func (m *GetContentsRequest) GetCategoryId() int32 {
	if m != nil {
		return m.CategoryId
	}
	return 0
}

func (m *GetContentsRequest) GetTypeId() int32 {
	if m != nil {
		return m.TypeId
	}
	return 0
}

func (m *GetContentsRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GetContentsRequest) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *GetContentsRequest) GetPageNum() int32 {
	if m != nil {
		return m.PageNum
	}
	return 0
}

type GetContentsResponse struct {
	Results              []*Content `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	PagesCount           int32      `protobuf:"varint,2,opt,name=pages_count,json=pagesCount,proto3" json:"pages_count,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GetContentsResponse) Reset()         { *m = GetContentsResponse{} }
func (m *GetContentsResponse) String() string { return proto.CompactTextString(m) }
func (*GetContentsResponse) ProtoMessage()    {}
func (*GetContentsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_content_0073c56b4875ea38, []int{5}
}
func (m *GetContentsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetContentsResponse.Unmarshal(m, b)
}
func (m *GetContentsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetContentsResponse.Marshal(b, m, deterministic)
}
func (dst *GetContentsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetContentsResponse.Merge(dst, src)
}
func (m *GetContentsResponse) XXX_Size() int {
	return xxx_messageInfo_GetContentsResponse.Size(m)
}
func (m *GetContentsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetContentsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetContentsResponse proto.InternalMessageInfo

func (m *GetContentsResponse) GetResults() []*Content {
	if m != nil {
		return m.Results
	}
	return nil
}

func (m *GetContentsResponse) GetPagesCount() int32 {
	if m != nil {
		return m.PagesCount
	}
	return 0
}

type UpdateContentResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateContentResponse) Reset()         { *m = UpdateContentResponse{} }
func (m *UpdateContentResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateContentResponse) ProtoMessage()    {}
func (*UpdateContentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_content_0073c56b4875ea38, []int{6}
}
func (m *UpdateContentResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateContentResponse.Unmarshal(m, b)
}
func (m *UpdateContentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateContentResponse.Marshal(b, m, deterministic)
}
func (dst *UpdateContentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateContentResponse.Merge(dst, src)
}
func (m *UpdateContentResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateContentResponse.Size(m)
}
func (m *UpdateContentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateContentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateContentResponse proto.InternalMessageInfo

type ContentType struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ContentType) Reset()         { *m = ContentType{} }
func (m *ContentType) String() string { return proto.CompactTextString(m) }
func (*ContentType) ProtoMessage()    {}
func (*ContentType) Descriptor() ([]byte, []int) {
	return fileDescriptor_content_0073c56b4875ea38, []int{7}
}
func (m *ContentType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContentType.Unmarshal(m, b)
}
func (m *ContentType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContentType.Marshal(b, m, deterministic)
}
func (dst *ContentType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContentType.Merge(dst, src)
}
func (m *ContentType) XXX_Size() int {
	return xxx_messageInfo_ContentType.Size(m)
}
func (m *ContentType) XXX_DiscardUnknown() {
	xxx_messageInfo_ContentType.DiscardUnknown(m)
}

var xxx_messageInfo_ContentType proto.InternalMessageInfo

func (m *ContentType) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ContentType) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ContentType) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type CreateContentTypeRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description          string   `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateContentTypeRequest) Reset()         { *m = CreateContentTypeRequest{} }
func (m *CreateContentTypeRequest) String() string { return proto.CompactTextString(m) }
func (*CreateContentTypeRequest) ProtoMessage()    {}
func (*CreateContentTypeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_content_0073c56b4875ea38, []int{8}
}
func (m *CreateContentTypeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateContentTypeRequest.Unmarshal(m, b)
}
func (m *CreateContentTypeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateContentTypeRequest.Marshal(b, m, deterministic)
}
func (dst *CreateContentTypeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateContentTypeRequest.Merge(dst, src)
}
func (m *CreateContentTypeRequest) XXX_Size() int {
	return xxx_messageInfo_CreateContentTypeRequest.Size(m)
}
func (m *CreateContentTypeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateContentTypeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateContentTypeRequest proto.InternalMessageInfo

func (m *CreateContentTypeRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateContentTypeRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type CreateContentTypeResponse struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateContentTypeResponse) Reset()         { *m = CreateContentTypeResponse{} }
func (m *CreateContentTypeResponse) String() string { return proto.CompactTextString(m) }
func (*CreateContentTypeResponse) ProtoMessage()    {}
func (*CreateContentTypeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_content_0073c56b4875ea38, []int{9}
}
func (m *CreateContentTypeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateContentTypeResponse.Unmarshal(m, b)
}
func (m *CreateContentTypeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateContentTypeResponse.Marshal(b, m, deterministic)
}
func (dst *CreateContentTypeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateContentTypeResponse.Merge(dst, src)
}
func (m *CreateContentTypeResponse) XXX_Size() int {
	return xxx_messageInfo_CreateContentTypeResponse.Size(m)
}
func (m *CreateContentTypeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateContentTypeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateContentTypeResponse proto.InternalMessageInfo

func (m *CreateContentTypeResponse) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type GetContentTypeRequest struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetContentTypeRequest) Reset()         { *m = GetContentTypeRequest{} }
func (m *GetContentTypeRequest) String() string { return proto.CompactTextString(m) }
func (*GetContentTypeRequest) ProtoMessage()    {}
func (*GetContentTypeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_content_0073c56b4875ea38, []int{10}
}
func (m *GetContentTypeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetContentTypeRequest.Unmarshal(m, b)
}
func (m *GetContentTypeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetContentTypeRequest.Marshal(b, m, deterministic)
}
func (dst *GetContentTypeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetContentTypeRequest.Merge(dst, src)
}
func (m *GetContentTypeRequest) XXX_Size() int {
	return xxx_messageInfo_GetContentTypeRequest.Size(m)
}
func (m *GetContentTypeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetContentTypeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetContentTypeRequest proto.InternalMessageInfo

func (m *GetContentTypeRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type UpdateContentTypeResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateContentTypeResponse) Reset()         { *m = UpdateContentTypeResponse{} }
func (m *UpdateContentTypeResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateContentTypeResponse) ProtoMessage()    {}
func (*UpdateContentTypeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_content_0073c56b4875ea38, []int{11}
}
func (m *UpdateContentTypeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateContentTypeResponse.Unmarshal(m, b)
}
func (m *UpdateContentTypeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateContentTypeResponse.Marshal(b, m, deterministic)
}
func (dst *UpdateContentTypeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateContentTypeResponse.Merge(dst, src)
}
func (m *UpdateContentTypeResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateContentTypeResponse.Size(m)
}
func (m *UpdateContentTypeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateContentTypeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateContentTypeResponse proto.InternalMessageInfo

type GetAllContentTypesRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAllContentTypesRequest) Reset()         { *m = GetAllContentTypesRequest{} }
func (m *GetAllContentTypesRequest) String() string { return proto.CompactTextString(m) }
func (*GetAllContentTypesRequest) ProtoMessage()    {}
func (*GetAllContentTypesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_content_0073c56b4875ea38, []int{12}
}
func (m *GetAllContentTypesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAllContentTypesRequest.Unmarshal(m, b)
}
func (m *GetAllContentTypesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAllContentTypesRequest.Marshal(b, m, deterministic)
}
func (dst *GetAllContentTypesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAllContentTypesRequest.Merge(dst, src)
}
func (m *GetAllContentTypesRequest) XXX_Size() int {
	return xxx_messageInfo_GetAllContentTypesRequest.Size(m)
}
func (m *GetAllContentTypesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAllContentTypesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAllContentTypesRequest proto.InternalMessageInfo

type GetAllContentTypesResponse struct {
	Results              []*ContentType `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *GetAllContentTypesResponse) Reset()         { *m = GetAllContentTypesResponse{} }
func (m *GetAllContentTypesResponse) String() string { return proto.CompactTextString(m) }
func (*GetAllContentTypesResponse) ProtoMessage()    {}
func (*GetAllContentTypesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_content_0073c56b4875ea38, []int{13}
}
func (m *GetAllContentTypesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAllContentTypesResponse.Unmarshal(m, b)
}
func (m *GetAllContentTypesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAllContentTypesResponse.Marshal(b, m, deterministic)
}
func (dst *GetAllContentTypesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAllContentTypesResponse.Merge(dst, src)
}
func (m *GetAllContentTypesResponse) XXX_Size() int {
	return xxx_messageInfo_GetAllContentTypesResponse.Size(m)
}
func (m *GetAllContentTypesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAllContentTypesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetAllContentTypesResponse proto.InternalMessageInfo

func (m *GetAllContentTypesResponse) GetResults() []*ContentType {
	if m != nil {
		return m.Results
	}
	return nil
}

type Category struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ParentId             int32    `protobuf:"varint,2,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description          string   `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Category) Reset()         { *m = Category{} }
func (m *Category) String() string { return proto.CompactTextString(m) }
func (*Category) ProtoMessage()    {}
func (*Category) Descriptor() ([]byte, []int) {
	return fileDescriptor_content_0073c56b4875ea38, []int{14}
}
func (m *Category) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Category.Unmarshal(m, b)
}
func (m *Category) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Category.Marshal(b, m, deterministic)
}
func (dst *Category) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Category.Merge(dst, src)
}
func (m *Category) XXX_Size() int {
	return xxx_messageInfo_Category.Size(m)
}
func (m *Category) XXX_DiscardUnknown() {
	xxx_messageInfo_Category.DiscardUnknown(m)
}

var xxx_messageInfo_Category proto.InternalMessageInfo

func (m *Category) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Category) GetParentId() int32 {
	if m != nil {
		return m.ParentId
	}
	return 0
}

func (m *Category) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Category) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type CreateCategoryRequest struct {
	ParentId             int32    `protobuf:"varint,1,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateCategoryRequest) Reset()         { *m = CreateCategoryRequest{} }
func (m *CreateCategoryRequest) String() string { return proto.CompactTextString(m) }
func (*CreateCategoryRequest) ProtoMessage()    {}
func (*CreateCategoryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_content_0073c56b4875ea38, []int{15}
}
func (m *CreateCategoryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateCategoryRequest.Unmarshal(m, b)
}
func (m *CreateCategoryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateCategoryRequest.Marshal(b, m, deterministic)
}
func (dst *CreateCategoryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateCategoryRequest.Merge(dst, src)
}
func (m *CreateCategoryRequest) XXX_Size() int {
	return xxx_messageInfo_CreateCategoryRequest.Size(m)
}
func (m *CreateCategoryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateCategoryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateCategoryRequest proto.InternalMessageInfo

func (m *CreateCategoryRequest) GetParentId() int32 {
	if m != nil {
		return m.ParentId
	}
	return 0
}

func (m *CreateCategoryRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateCategoryRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type CreateCategoryResponse struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateCategoryResponse) Reset()         { *m = CreateCategoryResponse{} }
func (m *CreateCategoryResponse) String() string { return proto.CompactTextString(m) }
func (*CreateCategoryResponse) ProtoMessage()    {}
func (*CreateCategoryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_content_0073c56b4875ea38, []int{16}
}
func (m *CreateCategoryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateCategoryResponse.Unmarshal(m, b)
}
func (m *CreateCategoryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateCategoryResponse.Marshal(b, m, deterministic)
}
func (dst *CreateCategoryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateCategoryResponse.Merge(dst, src)
}
func (m *CreateCategoryResponse) XXX_Size() int {
	return xxx_messageInfo_CreateCategoryResponse.Size(m)
}
func (m *CreateCategoryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateCategoryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateCategoryResponse proto.InternalMessageInfo

func (m *CreateCategoryResponse) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type GetCategoryRequest struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCategoryRequest) Reset()         { *m = GetCategoryRequest{} }
func (m *GetCategoryRequest) String() string { return proto.CompactTextString(m) }
func (*GetCategoryRequest) ProtoMessage()    {}
func (*GetCategoryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_content_0073c56b4875ea38, []int{17}
}
func (m *GetCategoryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCategoryRequest.Unmarshal(m, b)
}
func (m *GetCategoryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCategoryRequest.Marshal(b, m, deterministic)
}
func (dst *GetCategoryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCategoryRequest.Merge(dst, src)
}
func (m *GetCategoryRequest) XXX_Size() int {
	return xxx_messageInfo_GetCategoryRequest.Size(m)
}
func (m *GetCategoryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCategoryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetCategoryRequest proto.InternalMessageInfo

func (m *GetCategoryRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type UpdateCategoryResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateCategoryResponse) Reset()         { *m = UpdateCategoryResponse{} }
func (m *UpdateCategoryResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateCategoryResponse) ProtoMessage()    {}
func (*UpdateCategoryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_content_0073c56b4875ea38, []int{18}
}
func (m *UpdateCategoryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateCategoryResponse.Unmarshal(m, b)
}
func (m *UpdateCategoryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateCategoryResponse.Marshal(b, m, deterministic)
}
func (dst *UpdateCategoryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateCategoryResponse.Merge(dst, src)
}
func (m *UpdateCategoryResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateCategoryResponse.Size(m)
}
func (m *UpdateCategoryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateCategoryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateCategoryResponse proto.InternalMessageInfo

type GetAllCategoriesRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAllCategoriesRequest) Reset()         { *m = GetAllCategoriesRequest{} }
func (m *GetAllCategoriesRequest) String() string { return proto.CompactTextString(m) }
func (*GetAllCategoriesRequest) ProtoMessage()    {}
func (*GetAllCategoriesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_content_0073c56b4875ea38, []int{19}
}
func (m *GetAllCategoriesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAllCategoriesRequest.Unmarshal(m, b)
}
func (m *GetAllCategoriesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAllCategoriesRequest.Marshal(b, m, deterministic)
}
func (dst *GetAllCategoriesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAllCategoriesRequest.Merge(dst, src)
}
func (m *GetAllCategoriesRequest) XXX_Size() int {
	return xxx_messageInfo_GetAllCategoriesRequest.Size(m)
}
func (m *GetAllCategoriesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAllCategoriesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAllCategoriesRequest proto.InternalMessageInfo

type GetAllCategoriesResponse struct {
	Results              []*Category `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GetAllCategoriesResponse) Reset()         { *m = GetAllCategoriesResponse{} }
func (m *GetAllCategoriesResponse) String() string { return proto.CompactTextString(m) }
func (*GetAllCategoriesResponse) ProtoMessage()    {}
func (*GetAllCategoriesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_content_0073c56b4875ea38, []int{20}
}
func (m *GetAllCategoriesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAllCategoriesResponse.Unmarshal(m, b)
}
func (m *GetAllCategoriesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAllCategoriesResponse.Marshal(b, m, deterministic)
}
func (dst *GetAllCategoriesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAllCategoriesResponse.Merge(dst, src)
}
func (m *GetAllCategoriesResponse) XXX_Size() int {
	return xxx_messageInfo_GetAllCategoriesResponse.Size(m)
}
func (m *GetAllCategoriesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAllCategoriesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetAllCategoriesResponse proto.InternalMessageInfo

func (m *GetAllCategoriesResponse) GetResults() []*Category {
	if m != nil {
		return m.Results
	}
	return nil
}

func init() {
	proto.RegisterType((*Content)(nil), "content.Content")
	proto.RegisterType((*CreateContentRequest)(nil), "content.CreateContentRequest")
	proto.RegisterType((*CreateContentResponse)(nil), "content.CreateContentResponse")
	proto.RegisterType((*GetContentRequest)(nil), "content.GetContentRequest")
	proto.RegisterType((*GetContentsRequest)(nil), "content.GetContentsRequest")
	proto.RegisterType((*GetContentsResponse)(nil), "content.GetContentsResponse")
	proto.RegisterType((*UpdateContentResponse)(nil), "content.UpdateContentResponse")
	proto.RegisterType((*ContentType)(nil), "content.ContentType")
	proto.RegisterType((*CreateContentTypeRequest)(nil), "content.CreateContentTypeRequest")
	proto.RegisterType((*CreateContentTypeResponse)(nil), "content.CreateContentTypeResponse")
	proto.RegisterType((*GetContentTypeRequest)(nil), "content.GetContentTypeRequest")
	proto.RegisterType((*UpdateContentTypeResponse)(nil), "content.UpdateContentTypeResponse")
	proto.RegisterType((*GetAllContentTypesRequest)(nil), "content.GetAllContentTypesRequest")
	proto.RegisterType((*GetAllContentTypesResponse)(nil), "content.GetAllContentTypesResponse")
	proto.RegisterType((*Category)(nil), "content.Category")
	proto.RegisterType((*CreateCategoryRequest)(nil), "content.CreateCategoryRequest")
	proto.RegisterType((*CreateCategoryResponse)(nil), "content.CreateCategoryResponse")
	proto.RegisterType((*GetCategoryRequest)(nil), "content.GetCategoryRequest")
	proto.RegisterType((*UpdateCategoryResponse)(nil), "content.UpdateCategoryResponse")
	proto.RegisterType((*GetAllCategoriesRequest)(nil), "content.GetAllCategoriesRequest")
	proto.RegisterType((*GetAllCategoriesResponse)(nil), "content.GetAllCategoriesResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ContentServiceClient is the client API for ContentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ContentServiceClient interface {
	CreateContent(ctx context.Context, in *CreateContentRequest, opts ...grpc.CallOption) (*CreateContentResponse, error)
	UpdateContent(ctx context.Context, in *Content, opts ...grpc.CallOption) (*UpdateContentResponse, error)
	GetContent(ctx context.Context, in *GetContentRequest, opts ...grpc.CallOption) (*Content, error)
	GetContents(ctx context.Context, in *GetContentsRequest, opts ...grpc.CallOption) (*GetContentsResponse, error)
	CreateContentType(ctx context.Context, in *CreateContentTypeRequest, opts ...grpc.CallOption) (*CreateContentTypeResponse, error)
	UpdateContentType(ctx context.Context, in *ContentType, opts ...grpc.CallOption) (*UpdateContentTypeResponse, error)
	GetContentType(ctx context.Context, in *GetContentTypeRequest, opts ...grpc.CallOption) (*ContentType, error)
	GetAllContentTypes(ctx context.Context, in *GetAllContentTypesRequest, opts ...grpc.CallOption) (*GetAllContentTypesResponse, error)
	CreateCategory(ctx context.Context, in *CreateCategoryRequest, opts ...grpc.CallOption) (*CreateCategoryResponse, error)
	UpdateCategory(ctx context.Context, in *Category, opts ...grpc.CallOption) (*UpdateCategoryResponse, error)
	GetCategory(ctx context.Context, in *GetCategoryRequest, opts ...grpc.CallOption) (*Category, error)
	GetAllCategories(ctx context.Context, in *GetAllCategoriesRequest, opts ...grpc.CallOption) (*GetAllCategoriesResponse, error)
}

type contentServiceClient struct {
	cc *grpc.ClientConn
}

func NewContentServiceClient(cc *grpc.ClientConn) ContentServiceClient {
	return &contentServiceClient{cc}
}

func (c *contentServiceClient) CreateContent(ctx context.Context, in *CreateContentRequest, opts ...grpc.CallOption) (*CreateContentResponse, error) {
	out := new(CreateContentResponse)
	err := c.cc.Invoke(ctx, "/content.ContentService/CreateContent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contentServiceClient) UpdateContent(ctx context.Context, in *Content, opts ...grpc.CallOption) (*UpdateContentResponse, error) {
	out := new(UpdateContentResponse)
	err := c.cc.Invoke(ctx, "/content.ContentService/UpdateContent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contentServiceClient) GetContent(ctx context.Context, in *GetContentRequest, opts ...grpc.CallOption) (*Content, error) {
	out := new(Content)
	err := c.cc.Invoke(ctx, "/content.ContentService/GetContent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contentServiceClient) GetContents(ctx context.Context, in *GetContentsRequest, opts ...grpc.CallOption) (*GetContentsResponse, error) {
	out := new(GetContentsResponse)
	err := c.cc.Invoke(ctx, "/content.ContentService/GetContents", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contentServiceClient) CreateContentType(ctx context.Context, in *CreateContentTypeRequest, opts ...grpc.CallOption) (*CreateContentTypeResponse, error) {
	out := new(CreateContentTypeResponse)
	err := c.cc.Invoke(ctx, "/content.ContentService/CreateContentType", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contentServiceClient) UpdateContentType(ctx context.Context, in *ContentType, opts ...grpc.CallOption) (*UpdateContentTypeResponse, error) {
	out := new(UpdateContentTypeResponse)
	err := c.cc.Invoke(ctx, "/content.ContentService/UpdateContentType", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contentServiceClient) GetContentType(ctx context.Context, in *GetContentTypeRequest, opts ...grpc.CallOption) (*ContentType, error) {
	out := new(ContentType)
	err := c.cc.Invoke(ctx, "/content.ContentService/GetContentType", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contentServiceClient) GetAllContentTypes(ctx context.Context, in *GetAllContentTypesRequest, opts ...grpc.CallOption) (*GetAllContentTypesResponse, error) {
	out := new(GetAllContentTypesResponse)
	err := c.cc.Invoke(ctx, "/content.ContentService/GetAllContentTypes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contentServiceClient) CreateCategory(ctx context.Context, in *CreateCategoryRequest, opts ...grpc.CallOption) (*CreateCategoryResponse, error) {
	out := new(CreateCategoryResponse)
	err := c.cc.Invoke(ctx, "/content.ContentService/CreateCategory", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contentServiceClient) UpdateCategory(ctx context.Context, in *Category, opts ...grpc.CallOption) (*UpdateCategoryResponse, error) {
	out := new(UpdateCategoryResponse)
	err := c.cc.Invoke(ctx, "/content.ContentService/UpdateCategory", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contentServiceClient) GetCategory(ctx context.Context, in *GetCategoryRequest, opts ...grpc.CallOption) (*Category, error) {
	out := new(Category)
	err := c.cc.Invoke(ctx, "/content.ContentService/GetCategory", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contentServiceClient) GetAllCategories(ctx context.Context, in *GetAllCategoriesRequest, opts ...grpc.CallOption) (*GetAllCategoriesResponse, error) {
	out := new(GetAllCategoriesResponse)
	err := c.cc.Invoke(ctx, "/content.ContentService/GetAllCategories", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ContentServiceServer is the server API for ContentService service.
type ContentServiceServer interface {
	CreateContent(context.Context, *CreateContentRequest) (*CreateContentResponse, error)
	UpdateContent(context.Context, *Content) (*UpdateContentResponse, error)
	GetContent(context.Context, *GetContentRequest) (*Content, error)
	GetContents(context.Context, *GetContentsRequest) (*GetContentsResponse, error)
	CreateContentType(context.Context, *CreateContentTypeRequest) (*CreateContentTypeResponse, error)
	UpdateContentType(context.Context, *ContentType) (*UpdateContentTypeResponse, error)
	GetContentType(context.Context, *GetContentTypeRequest) (*ContentType, error)
	GetAllContentTypes(context.Context, *GetAllContentTypesRequest) (*GetAllContentTypesResponse, error)
	CreateCategory(context.Context, *CreateCategoryRequest) (*CreateCategoryResponse, error)
	UpdateCategory(context.Context, *Category) (*UpdateCategoryResponse, error)
	GetCategory(context.Context, *GetCategoryRequest) (*Category, error)
	GetAllCategories(context.Context, *GetAllCategoriesRequest) (*GetAllCategoriesResponse, error)
}

func RegisterContentServiceServer(s *grpc.Server, srv ContentServiceServer) {
	s.RegisterService(&_ContentService_serviceDesc, srv)
}

func _ContentService_CreateContent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateContentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContentServiceServer).CreateContent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/content.ContentService/CreateContent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContentServiceServer).CreateContent(ctx, req.(*CreateContentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContentService_UpdateContent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Content)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContentServiceServer).UpdateContent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/content.ContentService/UpdateContent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContentServiceServer).UpdateContent(ctx, req.(*Content))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContentService_GetContent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetContentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContentServiceServer).GetContent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/content.ContentService/GetContent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContentServiceServer).GetContent(ctx, req.(*GetContentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContentService_GetContents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetContentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContentServiceServer).GetContents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/content.ContentService/GetContents",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContentServiceServer).GetContents(ctx, req.(*GetContentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContentService_CreateContentType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateContentTypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContentServiceServer).CreateContentType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/content.ContentService/CreateContentType",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContentServiceServer).CreateContentType(ctx, req.(*CreateContentTypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContentService_UpdateContentType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ContentType)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContentServiceServer).UpdateContentType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/content.ContentService/UpdateContentType",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContentServiceServer).UpdateContentType(ctx, req.(*ContentType))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContentService_GetContentType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetContentTypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContentServiceServer).GetContentType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/content.ContentService/GetContentType",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContentServiceServer).GetContentType(ctx, req.(*GetContentTypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContentService_GetAllContentTypes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllContentTypesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContentServiceServer).GetAllContentTypes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/content.ContentService/GetAllContentTypes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContentServiceServer).GetAllContentTypes(ctx, req.(*GetAllContentTypesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContentService_CreateCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCategoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContentServiceServer).CreateCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/content.ContentService/CreateCategory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContentServiceServer).CreateCategory(ctx, req.(*CreateCategoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContentService_UpdateCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Category)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContentServiceServer).UpdateCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/content.ContentService/UpdateCategory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContentServiceServer).UpdateCategory(ctx, req.(*Category))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContentService_GetCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCategoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContentServiceServer).GetCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/content.ContentService/GetCategory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContentServiceServer).GetCategory(ctx, req.(*GetCategoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContentService_GetAllCategories_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllCategoriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContentServiceServer).GetAllCategories(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/content.ContentService/GetAllCategories",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContentServiceServer).GetAllCategories(ctx, req.(*GetAllCategoriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ContentService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "content.ContentService",
	HandlerType: (*ContentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateContent",
			Handler:    _ContentService_CreateContent_Handler,
		},
		{
			MethodName: "UpdateContent",
			Handler:    _ContentService_UpdateContent_Handler,
		},
		{
			MethodName: "GetContent",
			Handler:    _ContentService_GetContent_Handler,
		},
		{
			MethodName: "GetContents",
			Handler:    _ContentService_GetContents_Handler,
		},
		{
			MethodName: "CreateContentType",
			Handler:    _ContentService_CreateContentType_Handler,
		},
		{
			MethodName: "UpdateContentType",
			Handler:    _ContentService_UpdateContentType_Handler,
		},
		{
			MethodName: "GetContentType",
			Handler:    _ContentService_GetContentType_Handler,
		},
		{
			MethodName: "GetAllContentTypes",
			Handler:    _ContentService_GetAllContentTypes_Handler,
		},
		{
			MethodName: "CreateCategory",
			Handler:    _ContentService_CreateCategory_Handler,
		},
		{
			MethodName: "UpdateCategory",
			Handler:    _ContentService_UpdateCategory_Handler,
		},
		{
			MethodName: "GetCategory",
			Handler:    _ContentService_GetCategory_Handler,
		},
		{
			MethodName: "GetAllCategories",
			Handler:    _ContentService_GetAllCategories_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "content.proto",
}

func init() { proto.RegisterFile("content.proto", fileDescriptor_content_0073c56b4875ea38) }

var fileDescriptor_content_0073c56b4875ea38 = []byte{
	// 746 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x94, 0x56, 0xdb, 0x6e, 0xd3, 0x4c,
	0x10, 0x96, 0x93, 0x26, 0x4e, 0x27, 0x7f, 0xa2, 0x66, 0xfe, 0x1e, 0x1c, 0x17, 0x7a, 0xd8, 0x22,
	0x51, 0x51, 0xa9, 0x17, 0xe5, 0x0e, 0x89, 0x8b, 0x2a, 0x88, 0x82, 0x04, 0x15, 0xa4, 0x54, 0x48,
	0x48, 0x28, 0xca, 0x61, 0x55, 0x8c, 0x12, 0x3b, 0xf8, 0x80, 0x54, 0x1e, 0x85, 0x67, 0xe0, 0xa1,
	0x90, 0x78, 0x11, 0xec, 0xf5, 0x6e, 0xb2, 0xde, 0x5d, 0xa7, 0xe5, 0x6e, 0x3d, 0x33, 0xfb, 0xcd,
	0xe9, 0xfb, 0x56, 0x86, 0xd6, 0x38, 0xf0, 0x63, 0xea, 0xc7, 0xa7, 0xf3, 0x30, 0x88, 0x03, 0xb4,
	0xf9, 0x27, 0xf9, 0x63, 0x81, 0xdd, 0xcb, 0xcf, 0xd8, 0x86, 0x8a, 0x37, 0x71, 0xac, 0x03, 0xeb,
	0xb8, 0xd6, 0x4f, 0x4f, 0xb8, 0x0f, 0xcd, 0xf1, 0x30, 0xa6, 0x37, 0x41, 0x78, 0x3b, 0x48, 0x1d,
	0x15, 0xe6, 0x00, 0x61, 0x7a, 0x3d, 0x41, 0x84, 0x35, 0x7f, 0x38, 0xa3, 0x4e, 0x35, 0xf5, 0xac,
	0xf7, 0xd9, 0x19, 0x77, 0xc0, 0x8e, 0x6f, 0xe7, 0x34, 0xbb, 0xb0, 0xc6, 0x2e, 0xd4, 0xb3, 0xcf,
	0x34, 0xf8, 0x00, 0x9a, 0x13, 0x1a, 0x8d, 0x43, 0x6f, 0x1e, 0x7b, 0x81, 0xef, 0xd4, 0xd8, 0x1d,
	0xd9, 0x84, 0x47, 0xd0, 0x8a, 0xbf, 0x24, 0xb3, 0x91, 0x3f, 0xf4, 0xa6, 0x83, 0x24, 0x9c, 0x3a,
	0x75, 0x16, 0xf3, 0xdf, 0xc2, 0x78, 0x1d, 0x4e, 0x59, 0x51, 0x79, 0xbd, 0x2c, 0xc4, 0x66, 0x21,
	0xc0, 0x4d, 0x59, 0x40, 0x5a, 0x54, 0xe4, 0xfd, 0xa0, 0x4e, 0x83, 0x65, 0x67, 0x67, 0xf2, 0xdb,
	0x82, 0xcd, 0x5e, 0x48, 0xd3, 0xca, 0x79, 0xaf, 0x7d, 0xfa, 0x2d, 0xa1, 0x51, 0xac, 0xb6, 0x68,
	0x95, 0xb6, 0x58, 0x31, 0xb7, 0x58, 0x5d, 0xd5, 0xe2, 0xda, 0x3d, 0x5a, 0xac, 0xdd, 0xdd, 0x62,
	0xbd, 0xb4, 0x45, 0x5b, 0x6a, 0xf1, 0x31, 0x6c, 0x29, 0x1d, 0x46, 0xf3, 0xc0, 0x8f, 0xa8, 0xba,
	0x55, 0x72, 0x04, 0x9d, 0x0b, 0x1a, 0x2b, 0x73, 0x50, 0x83, 0x7e, 0x5a, 0x80, 0xcb, 0xa8, 0xe8,
	0xde, 0xe3, 0x92, 0x46, 0x53, 0x29, 0x8c, 0xc6, 0x44, 0x95, 0x5d, 0x58, 0x9f, 0x0f, 0x6f, 0xe8,
	0x80, 0xf5, 0x92, 0x93, 0xa5, 0x91, 0x19, 0xae, 0xd2, 0x6f, 0xec, 0x02, 0x3b, 0x0f, 0xfc, 0x64,
	0xc6, 0x86, 0x54, 0xeb, 0xdb, 0xd9, 0xf7, 0x65, 0x32, 0x23, 0x23, 0xf8, 0xbf, 0x50, 0x1b, 0x6f,
	0xf4, 0x09, 0xd8, 0x21, 0x8d, 0x92, 0x69, 0x1c, 0xa5, 0x85, 0x55, 0x8f, 0x9b, 0x67, 0x1b, 0xa7,
	0x82, 0xf4, 0xa2, 0x5b, 0x11, 0x90, 0x35, 0x92, 0xa1, 0x45, 0x83, 0x71, 0x90, 0xf8, 0xb1, 0xa0,
	0x36, 0x33, 0xf5, 0x32, 0x0b, 0xd9, 0x81, 0xad, 0xeb, 0xf9, 0x44, 0x1f, 0x27, 0xb9, 0x82, 0x26,
	0x37, 0x7d, 0x48, 0x3b, 0xd3, 0x34, 0x63, 0xe2, 0x8b, 0x42, 0x8b, 0xaa, 0x46, 0x0b, 0xf2, 0x0e,
	0x9c, 0xc2, 0xf2, 0x32, 0x68, 0x31, 0x73, 0x81, 0x68, 0x95, 0x23, 0x56, 0x74, 0xc4, 0x13, 0xe8,
	0x1a, 0x10, 0x4b, 0x28, 0x91, 0x72, 0x67, 0x39, 0x50, 0x39, 0xb7, 0x1a, 0xb8, 0x0b, 0xdd, 0xc2,
	0x54, 0x64, 0xd4, 0xcc, 0x99, 0xa2, 0x9c, 0x4f, 0xa7, 0x92, 0x53, 0x30, 0x87, 0xbc, 0x01, 0xd7,
	0xe4, 0xe4, 0x05, 0x9d, 0xaa, 0xab, 0xdb, 0x54, 0x57, 0xc7, 0x32, 0x89, 0x20, 0x32, 0x83, 0x46,
	0x8f, 0x93, 0x4e, 0xdb, 0x00, 0x63, 0x55, 0x98, 0x89, 0x67, 0x41, 0xc2, 0x46, 0x6e, 0x28, 0xa1,
	0xe1, 0x9d, 0xaa, 0x25, 0x5f, 0x17, 0xda, 0xe2, 0x49, 0xc5, 0x7c, 0x0a, 0xb9, 0xac, 0x92, 0x5c,
	0xff, 0x46, 0x85, 0x63, 0xd8, 0x56, 0x73, 0x95, 0x6c, 0xed, 0x51, 0x2e, 0x51, 0xa5, 0x24, 0x35,
	0xca, 0x81, 0x6d, 0xbe, 0x32, 0x05, 0x8f, 0x74, 0x61, 0x87, 0xaf, 0x24, 0xf7, 0x78, 0xcb, 0x6d,
	0x5d, 0x80, 0xa3, 0xbb, 0x78, 0x19, 0x27, 0xea, 0xae, 0x3a, 0xcb, 0x5d, 0x89, 0x14, 0x22, 0xe2,
	0xec, 0x97, 0x0d, 0x6d, 0xbe, 0xc1, 0x2b, 0x1a, 0x7e, 0xf7, 0xc6, 0x14, 0x2f, 0xa1, 0x55, 0x60,
	0x26, 0x3e, 0x5c, 0xde, 0x37, 0x3c, 0xd1, 0xee, 0x5e, 0x99, 0x9b, 0xd7, 0x73, 0x0e, 0xad, 0x02,
	0x27, 0x51, 0x93, 0xbd, 0x04, 0x61, 0xd4, 0x34, 0x3e, 0x03, 0x58, 0xf2, 0x1f, 0xdd, 0x45, 0xb4,
	0xf6, 0x4e, 0xba, 0x1a, 0x36, 0xbe, 0x82, 0xa6, 0xf4, 0x18, 0xe1, 0xae, 0xe1, 0xb2, 0x18, 0xab,
	0xfb, 0xc0, 0xec, 0xe4, 0x55, 0x7c, 0x82, 0x8e, 0x26, 0x59, 0x3c, 0x34, 0x77, 0x2f, 0x89, 0xd4,
	0x25, 0xab, 0x42, 0x38, 0xf6, 0x5b, 0xe8, 0x68, 0xc2, 0x45, 0xa3, 0xc8, 0x24, 0xb8, 0x52, 0xa9,
	0xe3, 0x4b, 0x68, 0x17, 0x1f, 0x0c, 0xdc, 0x33, 0xb4, 0x26, 0x17, 0x69, 0xcc, 0x85, 0x9f, 0x19,
	0x85, 0x95, 0x57, 0x01, 0x89, 0x8c, 0x65, 0x7e, 0x4f, 0xdc, 0xa3, 0x95, 0x31, 0xbc, 0xcc, 0xf7,
	0x29, 0xf9, 0x0a, 0x5a, 0x42, 0x8d, 0x4c, 0x45, 0xf5, 0xb8, 0xfb, 0xa5, 0x7e, 0x0e, 0xf9, 0x02,
	0xda, 0x45, 0x39, 0xa1, 0x4e, 0x7f, 0x09, 0xc5, 0x2c, 0x3d, 0x7c, 0x9e, 0x93, 0x46, 0x40, 0x14,
	0x49, 0xa3, 0x94, 0xa4, 0xe3, 0xe3, 0x47, 0xd8, 0x50, 0xe5, 0x89, 0x07, 0xea, 0x40, 0x54, 0x51,
	0xbb, 0x87, 0x2b, 0x22, 0xf2, 0xba, 0x46, 0x75, 0xf6, 0x77, 0xf8, 0xf4, 0x6f, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x0c, 0x3b, 0xfa, 0xa8, 0x2e, 0x0a, 0x00, 0x00,
}
